name: weather_app
description: Test weather simple app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  equatable: ^2.0.5
  geolocator: ^9.0.2
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  share_plus: ^7.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 

flutter:
  uses-material-design: true
  assets:
  - .env
